[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["asgardeo_registrations_webhook"]
  name = "asgardeo_registrations_webhook"
  org = "tdorg"
  version = "0.1.0"

